GNB_parameters:
  advanced: advanced
  comments: null
  dependencies:
    model: GNB
    quantitative: false
  description: GNB Parameters. See https://scikit-learn.org/ for further reference
  group: modeling
  object_type: dictionary
  options: null
  value:
    priors:
      description: null
      object_type: list
      options:
      - null
      value: null
      writable: true
  writable: false
MD_settings:
  advanced: regular
  comments: null
  dependencies:
  - ext_input: false
  - input_type: molecule
  description: Settings for molecular descriptors (when needed)
  group: data
  object_type: dictionary
  options: null
  value:
    morgan_features:
      description: Whether to use or not feature-based invariants.
      object_type: boolean
      options:
      - true
      - false
      value: true
      writable: false
    morgan_radius:
      description: Morgan fingerprint radius
      object_type: int
      options:
      - null
      value: 2
      writable: true
  writable: false
ModelValidationCV:
  advanced: regular
  comments: null
  dependencies: null
  description: Selection of cross-validation method
  group: modeling
  object_type: string
  options:
  - loo
  - kfold
  - lpo
  value: kfold
  writable: false
ModelValidationN:
  advanced: regular
  comments: null
  dependencies:
    ModelValidationCV: kfold
  description: Number of folds
  group: modeling
  object_type: int
  options: null
  value: 5
  writable: true
ModelValidationP:
  advanced: regular
  comments: null
  dependencies:
    ModelValidationCV: lpo
  description: Size of the test set
  group: modeling
  object_type: int
  options: null
  value: 1
  writable: true
PLSDA_optimize:
  advanced: advanced
  comments: null
  dependencies:
    model: PLSDA
    quantitative: false
  description: PLSDA optimize parameters
  group: modeling
  object_type: dictionary
  options: null
  value:
    n_components:
      description: null
      object_type: int
      options:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      value:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      writable: true
    scale:
      description: null
      object_type: boolean
      options:
      - true
      - false
      value:
      - true
      - false
      writable: false
    threshold:
      description: null
      object_type: float
      options:
      - 0.4
      - 0.5
      - 0.6
      value:
      - 0.4
      - 0.5
      - 0.6
      writable: true
    tol:
      description: null
      object_type: float
      options:
      - 6.0e-06
      value: 6.0e-06
      writable: true
  writable: false
PLSDA_parameters:
  advanced: advanced
  comments: null
  dependencies:
    model: PLSDA
    quantitative: false
  description: PLSDA Parameters
  group: modeling
  object_type: dictionary
  options: null
  value:
    n_components:
      description: Number of latent variables to extract
      object_type: int
      options:
      - null
      value: 2
      writable: true
    optimize:
      description: null
      object_type: string
      options:
      - manual
      - auto
      value: manual
      writable: true
    scale:
      description: Wether X variables should be scaled to unit variance
      object_type: boolean
      options:
      - true
      - false
      value: false
      writable: false
    threshold:
      description: null
      object_type: float
      options:
      - 0.5
      value: 0.5
      writable: true
    tol:
      description: Tolerance used in the iterative algorithm default 1e-06
      object_type: float
      options:
      - null
      value: 6.0e-06
      writable: true
  writable: false
PLSR_optimize:
  advanced: advanced
  comments: null
  dependencies:
    model: PLSR
    quantitative: true
  description: PLSR optimize parameters
  group: modeling
  object_type: dictionary
  options: null
  value:
    n_components:
      description: null
      object_type: list
      options:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      value:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      writable: true
  writable: false
PLSR_parameters:
  advanced: advanced
  comments: null
  dependencies:
    model: PLSR
    quantitative: true
  description: PLSR Parameters. See https://scikit-learn.org/ for further reference
  group: modeling
  object_type: dictionary
  options: null
  value:
    n_components:
      description: Number of latent variables to extract
      object_type: int
      options:
      - null
      value: 2
      writable: true
    optimize:
      description: null
      object_type: string
      options:
      - manual
      - auto
      value: manual
      writable: true
    scale:
      description: Wether X variables should be scaled to unit variance
      object_type: boolean
      options:
      - true
      - false
      value: false
      writable: false
    tol:
      description: Tolerance used in the iterative algorithm default 1e-06
      object_type: float
      options:
      - null
      value: 6.0e-06
      writable: true
  writable: false
RF_optimize:
  advanced: advanced
  comments: null
  dependencies:
    model: RF
    tune: true
  description: Random Forest Optimize parameters
  group: modeling
  object_type: dictionary
  options: null
  value:
    class_weight:
      description: null
      object_type: list
      options:
      - default
      - balanced
      value:
      - default
      - balanced
      writable: false
    max_features:
      description: null
      object_type: string
      options:
      - auto
      - sqrt
      - log2
      - null
      value:
      - sqrt
      - log2
      writable: false
    n_estimators:
      description: null
      max: 500
      min: 0
      object_type: int
      options: null
      value:
      - 50
      - 100
      writable: true
  writable: false
RF_parameters:
  advanced: advanced
  comments: null
  dependencies:
    model: RF
  description: Random Forest Parameters See https://scikit-learn.org/ for further
    reference
  group: modeling
  object_type: dictionary
  options: null
  value:
    class_weight:
      description: Weights associated with classes. If not given, all classes are
        supposed to have weight one
      object_type: string
      options:
      - null
      - balanced
      value: balanced
      writable: false
    max_depth:
      description: The maximum depth of the tree. If None, then nodes are expanded
        until all leaves are pure or until all leaves contain less than min_samples_split
        samples
      object_type: string
      options:
      - null
      value: null
      writable: true
    max_features:
      description: The maximum depth of the tree. If auto, then max_features=sqrt(n_features).
        If sqrt, idem as auto. If log2, then max_features=log2(n_features). If None,
        then max_features=n_features.
      object_type: string
      options:
      - auto
      - sqrt
      - log2
      - null
      value: sqrt
      writable: false
    n_estimators:
      description: The number of trees in the forest
      max: 500
      min: 1
      object_type: int
      options:
      - 50
      - 100
      - 150
      value: 200
      writable: true
    oob_score:
      description: Whether to use out-of-bag samples to estimate the generalization
        accuracy
      object_type: boolean
      options:
      - true
      - false
      value: true
      writable: false
    random_state:
      description: Random seed
      object_type: int
      options:
      - 46
      - null
      value: 46
      writable: true
  writable: false
SDFile_activity:
  advanced: regular
  comments: null
  dependencies:
    input_type: molecule
  description: Name of the activity field in the SDF file
  group: data
  object_type: string
  options: null
  value: activity
  writable: true
SDFile_experimental:
  advanced: advanced
  comments: null
  dependencies:
    input_type: molecule
  description: Experimental measure field in the SDF file
  group: data
  object_type: string
  options: null
  value: null
  writable: true
SDFile_name:
  advanced: regular
  comments: null
  dependencies:
    input_type: molecule
  description: Name of the identifier field in the SDF file
  group: data
  object_type: list
  options: null
  value:
  - GENERIC_NAME
  - name
  writable: true
SVM_optimize:
  advanced: advanced
  comments: null
  dependencies:
    model: SVM
  description: SVM optimize parameters
  group: modeling
  object_type: dictionary
  options: null
  value:
    C:
      description: null
      object_type: float
      options:
      - null
      - 1
      - 3
      - 5
      value:
      - 1
      - 10
      - 100
      writable: true
    class_weight:
      description: null
      object_type: list
      options:
      - default
      - balanced
      value:
      - default
      - balanced
      writable: false
    coef0:
      description: null
      object_type: float
      options:
      - null
      - 0
      - 0.8
      - 100
      value:
      - 0
      - 0.8
      - 100
      writable: true
    degree:
      description: null
      object_type: int
      options:
      - null
      - 1
      - 3
      - 5
      value:
      - 1
      - 3
      - 5
      writable: true
    gamma:
      description: null
      object_type: float
      options:
      - null
      - auto
      value:
      - auto
      writable: true
    kernel:
      description: null
      object_type: string
      options:
      - null
      - rfb
      - linear
      - poly
      value:
      - rbf
      writable: false
    probability:
      description: null
      object_type: boolean
      options:
      - true
      - false
      value:
      - true
      writable: false
    shrinking:
      description: null
      object_type: boolean
      options:
      - true
      - false
      value:
      - true
      writable: false
  writable: false
SVM_parameters:
  advanced: advanced
  comments: null
  dependencies:
    model: SVM
  description: SVM Parameters. See https://scikit-learn.org/ for further reference
  group: modeling
  object_type: dictionary
  options: null
  value:
    C:
      description: Penalty parameter C of the error term.
      object_type: float
      options:
      - null
      value: 1
      writable: true
    class_weight:
      description: Set the parameter C of class i to class_weight[i]*C for SVC. If
        not given, all classes are supposed to have weight one.
      object_type: string
      options:
      - null
      - balanced
      value: null
      writable: false
    coef0:
      description: Independent term in kernel function. It is only significant in
        poly and sigmoid.
      object_type: float
      options:
      - null
      value: 0
      writable: true
    degree:
      description: Degree of the polynomial kernel function (poly). Ignored by all
        other kernels.
      object_type: int
      options:
      - null
      value: 3
      writable: true
    gamma:
      description: Kernel coefficient for rbf, poly and sigmoid.
      object_type: float
      options:
      - null
      value: auto
      writable: true
    kernel:
      description: Specifies the kernel type to be used in the algorithm.
      object_type: string
      options:
      - null
      - rbf
      - linear
      - poly
      value: rbf
      writable: false
    probability:
      description: Whether to enable probability estimates.
      object_type: boolean
      options:
      - true
      - false
      value: true
      writable: false
    random_state:
      description: Random seed
      object_type: int
      options:
      - 46
      - null
      value: 46
      writable: true
    shrinking:
      description: Whether to use the shrinking heuristic.
      object_type: boolean
      options:
      - true
      - false
      value: true
      writable: false
  writable: false
TSV_activity:
  advanced: regular
  comments: null
  dependencies:
    input_type: data
  description: Name of the activity field in the TSV file
  group: data
  object_type: string
  options: null
  value: activity
  writable: true
TSV_objnames:
  advanced: regular
  comments: null
  dependencies:
    input_type: data
  description: True if object names in first column of data matrix
  group: data
  object_type: boolean
  options:
  - true
  - false
  value: true
  writable: false
TSV_varnames:
  advanced: regular
  comments: null
  dependencies:
    input_type: data
  description: True if variable names in first row of data matrix
  group: data
  object_type: boolean
  options:
  - true
  - false
  value: true
  writable: false
computeMD_method:
  advanced: regular
  comments: ''
  dependencies:
  - ext_input:false
  - input_type:molecule
  description: Selection of molecular descriptors to be used in model generation
  group: data
  object_type: list
  options:
  - RDKit_properties
  - RDKit_md
  - morganFP
  - padel
  - custom
  value:
  - RDKit_properties
  writable: false
confidential:
  advanced: regular
  comments: 'WARNING: TO IMPLEMENT'
  dependencies: null
  description: Confidentiality of the model. If True flame will remove all structures
    from build and prediction process
  group: preferences
  object_type: boolean
  options:
  - true
  - false
  value: false
  writable: false
conformal:
  advanced: regular
  comments: So far it can not be applied to PLSDA
  dependencies:
    model: RF
  description: If true, use the conformal variant of the selected modeling method,
    when available
  group: modeling
  object_type: boolean
  options:
  - true
  - false
  value: true
  writable: false
conformalSignificance:
  advanced: regular
  comments: So far it can not be applied to PLSDA
  dependencies:
    conformal: true
  description: Conformal estimator significance (from 0 to 1)
  group: modeling
  max: 1
  min: 0
  object_type: float
  options: null
  value: 0.2
  writable: true
convert3D_method:
  advanced: regular
  comments: null
  dependencies:
    input_type: molecule
  description: Selection of a 3D conversion method
  group: data
  object_type: string
  options:
  - ETKDG
  - null
  value: null
  writable: false
endpoint:
  value: Erik_Model
ext_input:
  advanced: advanced
  comments: null
  dependencies: null
  description: Whether to use or not external input source (from other models)
  group: data
  object_type: boolean
  options:
  - true
  - false
  value: false
  writable: false
feature_number:
  advanced: regular
  comments: null
  dependencies:
    feature_selection: Kbest
  description: Number of features to keep
  group: modeling
  object_type: string
  options:
  - auto
  value: auto
  writable: true
feature_selection:
  advanced: regular
  comments: null
  dependencies: null
  description: Whether to perform or not feature selection
  group: modeling
  object_type: string
  options:
  - null
  - Kbest
  value: null
  writable: false
imbalance:
  advanced: regular
  comments: null
  dependencies: null
  description: Whether to perform or not sub/over sampling strategies
  group: modeling
  object_type: string
  options:
  - null
  - simple_subsampling
  value: null
  writable: false
input_type:
  advanced: regular
  comments: null
  dependencies: null
  description: Type of input data.
  group: data
  object_type: string
  options:
  - molecule
  - data
  - ext_data
  value: molecule
  writable: false
ionize_method:
  advanced: regular
  comments: null
  dependencies:
    input_type: molecule
  description: Selection of a ionization method
  group: data
  object_type: string
  options:
  - null
  - moka
  value: null
  writable: false
md5:
  value: 2edc461dee65a1f927df6e6c8ade4ae1
model:
  advanced: regular
  comments: null
  dependencies:
    input_type: molecule
  description: List of available algorithms
  group: modeling
  object_type: string
  options:
  - RF
  - SVM
  - PLSR
  - PLSDA
  - GNB
  value: RF
  writable: false
modelAutoscaling:
  advanced: regular
  comments: null
  dependencies: null
  description: Scaling method. Null means that raw, unscaled data, will be used
  group: data
  object_type: string
  options:
  - StandardScaler
  - MinMaxScaler
  - RobustScaler
  - null
  value: StandardScaler
  writable: false
model_path:
  value: /Users/phi/github/flame_API/flame_api/models/Erik_Model/dev
model_set:
  advanced: advanced
  comments: Values are obtained from available models
  dependencies:
    ext_input: true
  description: Selection of available models to get the input from
  group: data
  object_type: list
  options: null
  value: null
  writable: true
modelingToolkit:
  advanced: regular
  comments: null
  dependencies:
    input_type: molecule
  description: List of toolkits usable to build models
  group: modeling
  object_type: string
  options:
  - internal
  - R
  - KNIME
  - custom
  value: internal
  writable: false
mol_batch:
  advanced: regular
  comments: null
  dependencies: null
  description: How molecules are going to be processed
  group: preferences
  object_type: string
  options:
  - series
  - objects
  value: series
  writable: false
normalize_method:
  advanced: regular
  comments: null
  dependencies:
    input_type: molecule
  description: Selection of a standardization method
  group: data
  object_type: string
  options:
  - null
  - standardize
  value: standardize
  writable: false
numCPUs:
  advanced: advanced
  comments: null
  dependencies: null
  description: Number of independent threads used to compute MD
  group: preferences
  object_type: int
  options:
  - null
  value: 1
  writable: true
output_format:
  advanced: regular
  comments: null
  dependencies: null
  description: Output data format
  group: preferences
  object_type: list
  options:
  - JSON
  - TSV
  value: JSON
  writable: false
output_md:
  advanced: advanced
  comments: null
  dependencies: null
  description: Dump descriptors to a TSV file
  group: preferences
  object_type: boolean
  options:
  - true
  - false
  value: false
  writable: false
param_format:
  value: 2.0
quantitative:
  advanced: regular
  comments: null
  dependencies:
    input_type: molecule
  description: Should be true for quantitative endpoints andf false for qualitative
    endpoints
  group: data
  object_type: boolean
  options:
  - true
  - false
  value: false
  writable: false
tune:
  advanced: regular
  comments: It might last long
  dependencies: null
  description: Whether to perform or not algorithm hyperparameter optimization
  group: modeling
  object_type: boolean
  options:
  - true
  - false
  value: false
  writable: false
verbose_error:
  advanced: advanced
  comments: null
  dependencies: null
  description: When false, RDKit errors are captured and not shown
  group: preferences
  object_type: boolean
  options:
  - true
  - false
  value: true
  writable: false
version:
  value: 0
