---
swagger: "2.0"
info:
  description: "flame framework API (alpha)"
  version: "0.1"
  title: "Flame API"
  contact:
    email: "biel.stela@upf.edu"
  license:
    name: "GLP v3"
    url: "https://www.gnu.org/licenses/gpl-3.0.en.html"
host: "virtserver.swaggerhub.com"
basePath: "/flame"
tags:
- name: "predict"
  description: "Predict interface"
- name: "build"
  description: "Build models"
- name: "manage"
  description: "Manage models, versioning, delete, publish, etc."
schemes:
- "https"
paths:
  /predict:
    get:
      tags:
      - "predict"
      summary: "Prediction models listing"
      description: "Search for available models"
      operationId: "get_models"
      produces:
      - "application/json"
      parameters:
      - name: "searchString"
        in: "query"
        description: "pass an optional search string for looking up inventory"
        required: false
        type: "string"
      - name: "limit"
        in: "query"
        description: "maximum number of models to return"
        required: false
        type: "integer"
        maximum: 50
        minimum: 0
        format: "int32"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Model"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.predict_controller"
  /predict/{modelID}:
    post:
      tags:
      - "predict"
      summary: "adds molecules and runs prediction with specified model "
      operationId: "predict"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "modelID"
        in: "path"
        description: "model id to run prediction with"
        required: true
        type: "string"
      - name: "upfile"
        in: "formData"
        description: "The .sdf or mol file to upload."
        required: true
        type: "file"
      responses:
        200:
          description: "prerdiction successful"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Results"
      x-swagger-router-controller: "swagger_server.controllers.predict_controller"
  /info: {}
  /dir: {}
  /download: {}
  /addModel: {}
  /exportModel: {}
  /deleteFamily: {}
  /deleteVersion: {}
definitions:
  Model:
    type: "object"
    required:
    - "maintainer"
    - "modelID"
    - "name"
    - "version"
    properties:
      modelID:
        type: "string"
        format: "uuid"
        example: "d290f1ee"
      name:
        type: "string"
        example: "CACO2"
      maintainer:
        type: "string"
        example: "UPF"
      version:
        type: "string"
        format: "int32"
        example: "1.0"
    example:
      modelID: "d290f1ee"
      name: "CACO2"
      version: "1.0"
      maintainer: "UPF"
  Results:
    type: "object"
    properties:
      columnName:
        type: "string"
      description:
        type: "string"
      values:
        type: "array"
        items:
          type: "number"
    example:
      values:
      - 0.80082819046101150206595775671303272247314453125
      - 0.80082819046101150206595775671303272247314453125
      description: "description"
      columnName: "columnName"
