param_format: 
  value: 2.0

input_type:
  advanced: regular
  object_type: string
  writable: false
  value: molecule
  options:
    - molecule
    - data
    - ext_data
  description: Type of input data.
  dependencies: null
  comments: 
  group: data

modelAutoscaling:
  advanced: regular
  object_type: string
  writable: false
  value: StandardScaler
  options:
    - StandardScaler
    - MinMaxScaler
    - RobustScaler
    - null
  description: Scaling method. Null means that raw, unscaled data, will be used 
  dependencies: null
  comments: 
  group: data

normalize_method:
  advanced: regular
  object_type: string
  writable: false
  value: standardize
  options:
    - null
    - standardize
  description: Selection of a standardization method
  dependencies: 
    input_type: molecule
  comments: 
  group: data

ionize_method:
  advanced: regular
  object_type: string
  writable: false
  value: null
  options:
    - null
    - moka
  description: Selection of a ionization method
  dependencies: 
    input_type: molecule
  comments: 
  group: data

quantitative:
  advanced: regular
  object_type: boolean
  writable: false
  value: true
  options:
    - true
    - false
  description: Should be true for quantitative endpoints andf false for qualitative endpoints
  dependencies: 
    input_type: molecule
  comments: 
  group: data

convert3D_method:
  advanced: regular
  object_type: string
  writable: false
  value: null
  options:
    - ETKDG
    - null
  description: Selection of a 3D conversion method
  dependencies: 
    input_type: molecule
  comments: 
  group: data

SDFile_activity:
  advanced: regular
  object_type: string
  writable: true
  value: activity
  options: null
  description: Name of the activity field in the SDF file
  dependencies: 
    input_type: molecule
  comments: 
  group: data

SDFile_name:
  advanced: regular
  object_type: list
  writable: true
  value: 
    - GENERIC_NAME
    - name
  options: null
  description: Name of the identifier field in the SDF file
  dependencies: 
    input_type: molecule
  comments: 
  group: data

TSV_activity:
  advanced: regular
  object_type: string
  writable: true
  value: activity
  options: null
  description: Name of the activity field in the TSV file
  dependencies: 
    input_type: data
  comments: 
  group: data 

TSV_objnames:
  advanced: regular
  object_type: boolean
  writable: false
  value: true
  options: 
    - true
    - false
  description: True if object names in first column of data matrix
  dependencies: 
    input_type: data
  comments: 
  group: data 

TSV_varnames:
  advanced: regular
  object_type: boolean
  writable: false
  value: true
  options: 
    - true
    - false
  description: True if variable names in first row of data matrix
  dependencies: 
    input_type: data
  comments: 
  group: data 

computeMD_method:
  advanced: regular
  object_type: list
  writable: false
  value: 
    - RDKit_properties
  options: 
    - RDKit_properties 
    - RDKit_md
    - morganFP
    - padel
    - custom
  description: Selection of molecular descriptors to be used in model generation
  dependencies: 
    - ext_input:false
    - input_type:molecule
  comments: ""
  group: data

MD_settings:
  advanced: regular
  object_type: dictionary
  writable: false
  value: 
    morgan_features:
      object_type: boolean
      writable: false
      value: true
      options:
        - true
        - false
      description: Whether to use or not feature-based invariants.
    morgan_radius:
      object_type: int
      writable: true
      value: 2
      options:
        - null
      description: Morgan fingerprint radius
  options: null
  description: Settings for molecular descriptors (when needed) 
  dependencies: 
    - ext_input: false
    - input_type: molecule
  comments: 
  group: data 

ext_input:
  advanced: advanced
  object_type: boolean
  writable: false
  value: false
  options: 
    - true
    - false
  description: Whether to use or not external input source (from other models)
  dependencies: null
  comments: 
  group: data    

model_set:
  advanced: advanced
  object_type: list
  writable: true
  value: null
  options: null
  description: Selection of available models to get the input from
  dependencies: 
    ext_input: true
  comments: Values are obtained from available models
  group: data    

SDFile_experimental:
  advanced: advanced
  object_type: string
  writable: true
  value: null
  options: null
  description: Experimental measure field in the SDF file
  dependencies: 
    input_type: molecule
  comments: 
  group: data    

modelingToolkit:
  advanced: regular
  object_type: string
  writable: false
  value: internal
  options:
    - internal
    - R
    - KNIME
    - custom
  description: List of toolkits usable to build models
  dependencies: 
    input_type: molecule
  comments: 
  group: modeling

model:
  advanced: regular
  object_type: string
  writable: false
  value: RF
  options: 
    - RF
    - SVM
    - PLSR
    - PLSDA
    - GNB
  description: List of available algorithms
  dependencies: 
    input_type: molecule
  comments: 
  group: modeling

conformal:
  advanced: regular
  object_type: boolean
  writable: false
  value: true
  options: 
    - true
    - false
  description: If true, use the conformal variant of the selected modeling method, when available
  dependencies: 
    model: RF
  comments: So far it can not be applied to PLSDA
  group: modeling    

conformalSignificance:
  advanced: regular
  object_type: float
  writable: true
  value: 0.20
  options: null
  min: 0
  max: 1
  description: Conformal estimator significance (from 0 to 1)
  dependencies: 
    conformal: true
  comments: So far it can not be applied to PLSDA
  group: modeling

tune:
  advanced: regular
  object_type: boolean
  writable: false
  value: false
  options: 
    - true
    - false
  description: Whether to perform or not algorithm hyperparameter optimization
  dependencies: null
  comments: It might last long
  group: modeling

imbalance:
  advanced: regular
  object_type: string
  writable: false
  value: null
  options: 
    - null
    - simple_subsampling
  description: Whether to perform or not sub/over sampling strategies
  dependencies: null
  comments: 
  group: modeling

feature_selection:
  advanced: regular
  object_type: string
  writable: false
  value: null
  options: 
    - null
    - Kbest
  description: Whether to perform or not feature selection
  dependencies: null
  comments: 
  group: modeling

feature_number:
  advanced: regular
  object_type: string
  writable: true
  value: auto
  options: 
    - auto
  description: Number of features to keep
  dependencies: 
    feature_selection: Kbest
  comments: 
  group: modeling

ModelValidationCV:
  advanced: regular
  object_type: string
  writable: false
  value: loo
  options: 
    - loo
    - kfold
    - lpo
  description: Selection of cross-validation method
  dependencies: null
  comments: 
  group: modeling

ModelValidationN:
  advanced: regular
  object_type: int
  writable: true
  value: 2
  options: null
  description: Number of folds
  dependencies: 
    ModelValidationCV: kfold
  comments: 
  group: modeling

ModelValidationP:
  advanced: regular
  object_type: int
  writable: true
  value: 1
  options: null
  description: Size of the test set
  dependencies: 
    ModelValidationCV: lpo
  comments: 
  group: modeling

RF_parameters:
  advanced: advanced
  object_type: dictionary
  writable: false
  options: null
  value: 
    class_weight:
      object_type: string
      writable: false
      value: balanced
      options:
        - null
        - balanced
      description: Weights associated with classes. If not given, all classes are supposed to have weight one
    max_depth:
      object_type: string
      writable: true
      value: null
      options:
        - null
      description: The maximum depth of the tree. If None, then nodes are expanded until all leaves are pure or until all leaves contain less than min_samples_split samples
    max_features:
      object_type: string
      writable: false
      value: sqrt
      options: 
        - auto
        - sqrt
        - log2
        - null
      description: The maximum depth of the tree. If auto, then max_features=sqrt(n_features). If sqrt, idem as auto. If log2, then max_features=log2(n_features). If None, then max_features=n_features.
    n_estimators:
      object_type: int
      writable: true
      value: 200
      options: 
        - 50
        - 100
        - 150
      max: 500
      min: 1
      description: The number of trees in the forest 
    oob_score:
      object_type: boolean
      writable: false
      value: true 
      options: 
        - true
        - false
      description: Whether to use out-of-bag samples to estimate the generalization accuracy
    random_state:
      object_type: int
      writable: true
      value: 46
      options:
        - 46
        - null
      description: Random seed
  description: Random Forest Parameters See https://scikit-learn.org/ for further reference
  dependencies: 
    model: RF
  comments: 
  group: modeling

RF_optimize:
  advanced: advanced
  object_type: dictionary
  writable: false
  options: null
  value:
    class_weight:
      object_type: list
      writable: false
      value: 
        - default
        - balanced
      options:
        - default
        - balanced
      description: 
    max_features:
      object_type: string
      writable: false
      value: 
        - sqrt
        - log2
      options: 
        - auto
        - sqrt
        - log2
        - null
      description: 
    n_estimators:
      object_type: int
      writable: true
      value: 
        - 50
        - 100
      options: null
      max: 500
      min: 0
      description: 
  description: Random Forest Optimize parameters
  dependencies: 
    model: RF
    tune: true
  comments: 
  group: modeling

SVM_parameters:
  advanced: advanced
  object_type: dictionary
  writable: false
  options: null
  value:
    class_weight:
      object_type: string
      writable: false
      value: null
      options:
        - null
        - balanced
      description: Set the parameter C of class i to class_weight[i]*C for SVC. If not given, all classes are supposed to have weight one. 
    C:
      object_type: float
      writable: true
      value: 1.0
      options:
        - null
      description: Penalty parameter C of the error term.
    coef0:
      object_type: float
      writable: true
      value: 0.0
      options: 
        - null
      description: Independent term in kernel function. It is only significant in poly and sigmoid.
    degree:
      object_type: int
      writable: true
      value: 3
      options: 
        - null
      description: Degree of the polynomial kernel function (poly). Ignored by all other kernels.
    gamma:
      object_type: float
      writable: true
      value: auto 
      options: 
        - null
      description: Kernel coefficient for rbf, poly and sigmoid.
    random_state:
      object_type: int
      writable: true
      value: 46
      options:
        - 46
        - null
      description: Random seed
    kernel:
      object_type: string
      writable: false
      value: rbf
      options:
        - null
        - rbf
        - linear
        - poly
      description: Specifies the kernel type to be used in the algorithm. 
    probability:
      object_type: boolean 
      writable: false
      value: true
      options:
        - true
        - false
      description: Whether to enable probability estimates.
    shrinking: 
      object_type: boolean
      writable: false
      value: true
      options:
        - true
        - false
      description: Whether to use the shrinking heuristic.
  description: SVM Parameters. See https://scikit-learn.org/ for further reference
  dependencies: 
    model: SVM
  comments: 
  group: modeling

SVM_optimize:
  advanced: advanced
  object_type: dictionary
  writable: false
  options: null
  value:
    class_weight:
      object_type: list
      writable: false
      value: 
        - default
        - balanced
      options:
        - default
        - balanced
      description: 
    C:
      object_type: float
      writable: true
      value: 
        - 1
        - 10
        - 100
      options:
        - null
        - 1
        - 3
        - 5
      description: 
    coef0:
      object_type: float
      writable: true
      value:
        - 0
        - 0.8
        - 100
      options: 
        - null
        - 0
        - 0.8
        - 100
      description: 
    degree:
      object_type: int
      writable: true
      value:
        - 1
        - 3 
        - 5
      options: 
        - null
        - 1
        - 3 
        - 5
      description: 
    gamma:
      object_type: float
      writable: true
      value: 
        - auto 
      options: 
        - null
        - auto
      description: 
    kernel:
      object_type: string
      writable: false
      value: 
        - rbf
      options:
        - null
        - rfb
        - linear
        - poly  
      description: 
    probability:
      object_type: boolean 
      writable: false
      value: 
        - true
      options:
        - true
        - false
      description:
    shrinking: 
      object_type: boolean
      writable: false
      value: 
        - true
      options:
        - true
        - false
      description: 
  description: SVM optimize parameters
  dependencies: 
    model: SVM
  comments: 
  group: modeling

PLSR_parameters:
  advanced: advanced
  object_type: dictionary
  writable: false
  options: null
  value:
    scale:
      object_type: boolean
      writable: false
      value: false
      options:
        - true
        - false
      description: Wether X variables should be scaled to unit variance 
    tol:
      object_type: float
      writable: true
      value: 0.000006
      options:
        - null
      description: Tolerance used in the iterative algorithm default 1e-06
    n_components: 
      object_type: int
      writable: true
      value: 2
      options: 
        - null
      description: Number of latent variables to extract
    optimize:
      object_type: string
      writable: true
      value: manual
      options: 
        - manual
        - auto
      description: 
  description: PLSR Parameters. See https://scikit-learn.org/ for further reference
  dependencies: 
    model: PLSR
    quantitative: true
  comments: 
  group: modeling

PLSR_optimize:
  advanced: advanced
  object_type: dictionary
  writable: false
  options: null
  value:
    n_components:
      object_type: list
      writable: true
      value: 
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
      options: 
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
      description: 
  description: PLSR optimize parameters
  dependencies: 
    model: PLSR
    quantitative: true
  comments: 
  group: modeling

PLSDA_parameters:
  advanced: advanced
  object_type: dictionary
  writable: false
  options: null
  value:
    scale:
      object_type: boolean
      writable: false
      value: false
      options:
        - true
        - false
      description: Wether X variables should be scaled to unit variance
    tol:
      object_type: float
      writable: true
      value: 0.000006
      options:
        - null
      description: Tolerance used in the iterative algorithm default 1e-06
    n_components:
      object_type: int
      writable: true
      value: 2
      options: 
        - null
      description: Number of latent variables to extract
    optimize:
      object_type: string
      writable: true
      value: manual
      options: 
        - manual
        - auto
      description: 
    threshold:
      object_type: float
      writable: true
      value: 0.5
      options: 
        - 0.5
      description: 
  description: PLSDA Parameters
  dependencies: 
    model: PLSDA
    quantitative: false
  comments: 
  group: modeling

PLSDA_optimize:
  advanced: advanced
  object_type: dictionary
  writable: false
  options: null
  value:
    scale:
      object_type: boolean
      writable: false
      value: 
        - true
        - false
      options:
        - true
        - false
      description: 
    tol:
      object_type: float
      writable: true
      value: 0.000006
      options:
        - 0.000006
      description: 
    n_components:
      object_type: int
      writable: true
      value:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
      options: 
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
      description: 
    threshold:
      object_type: float
      writable: true
      value: 
        - 0.4
        - 0.5
        - 0.6
      options: 
        - 0.4
        - 0.5
        - 0.6
      description: 
  description: PLSDA optimize parameters
  dependencies: 
    model: PLSDA
    quantitative: false
  comments: 
  group: modeling

GNB_parameters:
  advanced: advanced
  object_type: dictionary
  writable: false
  options: null
  value:
    priors:
      object_type: list
      writable: true
      value: null
      options:
        - null
      description: 

  description: GNB Parameters. See https://scikit-learn.org/ for further reference
  dependencies: 
    model: GNB
    quantitative: false
  comments: 
  group: modeling

output_format:
  advanced: regular
  object_type: list
  writable: false
  value: JSON
  options:
    - JSON
    - TSV
  description: Output data format
  dependencies: null
  comments: 
  group: preferences

output_md:
  advanced: advanced
  object_type: boolean
  writable: false
  value: false
  options:
    - true
    - false
  description: Dump descriptors to a TSV file
  dependencies: null 
  comments: 
  group: preferences

verbose_error:
  advanced: advanced
  object_type: boolean
  writable: false
  value: true
  options:
    - true
    - false
  description: When false, RDKit errors are captured and not shown
  dependencies: null
  comments: 
  group: preferences

numCPUs:
  advanced: advanced
  object_type: int
  writable: true
  value: 1
  options:
    - null
  description: Number of independent threads used to compute MD
  dependencies: null
  comments: 
  group: preferences

mol_batch:
  advanced: regular
  object_type: string
  writable: false
  value: series
  options:
    - series
    - objects
  description: How molecules are going to be processed
  dependencies: null
  comments: 
  group: preferences

confidential:
  advanced: regular
  object_type: boolean
  writable: false
  value: False
  options:
    - True
    - False
  description: "Confidentiality of the model. If True flame will remove all
                structures from build and prediction process"
  dependencies: null
  comments: "WARNING: TO IMPLEMENT" 
  group: preferences


